// Auto-generated by `supabase gen types typescript --project-id <id> > src/types/database.ts`
// Placeholder until first migration is applied. Do not edit by hand.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
